## See https://docs.travis-ci.com/user/languages/r/
language: r 
sudo: false
r:
##  - oldrel
  - release
  - devel

cache: packages

before_install:
  - cd ./R2admb

notifications:
  email:
    on_success: change
    on_failure: change

